# Generated by Django 4.2.16 on 2024-11-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("street_number", models.CharField(max_length=10)),
                ("street_name", models.CharField(max_length=100)),
                (
                    "apartment_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("zip_code", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                ("registration_date", models.DateField()),
                (
                    "party_affiliation",
                    models.CharField(
                        choices=[
                            ("D", "Democrat"),
                            ("R", "Republican"),
                            ("U", "Unaffiliated"),
                            ("O", "Other"),
                        ],
                        max_length=1,
                    ),
                ),
                ("precinct_number", models.IntegerField()),
                ("v20state", models.BooleanField(default=False)),
                ("v21town", models.BooleanField(default=False)),
                ("v21primary", models.BooleanField(default=False)),
                ("v22general", models.BooleanField(default=False)),
                ("v23town", models.BooleanField(default=False)),
                ("voter_score", models.IntegerField()),
            ],
        ),
    ]
