# Generated by Django 4.2.16 on 2024-11-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0002_alter_voter_precinct_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="party_affiliation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D", "Democratic"),
                    ("R", "Republican"),
                    ("CC", "Constitution Party"),
                    ("L", "Libertarian Party"),
                    ("T", "Tea Party"),
                    ("O", "Other"),
                    ("G", "Green Party"),
                    ("J", "Independent Party"),
                    ("Q", "Reform Party"),
                    ("FF", "Freedom Party"),
                ],
                max_length=2,
            ),
        ),
    ]
