# Generated by Django 4.2.16 on 2024-11-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruiterprofile",
            name="name",
            field=models.CharField(default="anon", max_length=100),
            preserve_default=False,
        ),
    ]
