# Generated by Django 4.2.16 on 2024-12-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_recruiterprofile_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dancerprofile",
            old_name="userProfileDancer",
            new_name="dancerUser",
        ),
        migrations.RenameField(
            model_name="recruiterprofile",
            old_name="userProfileRecruiter",
            new_name="recruiterUser",
        ),
    ]
