# Generated by Django 4.2.16 on 2024-12-06 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0003_rename_userprofiledancer_dancerprofile_danceruser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dancerprofile",
            name="dancerUser",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dancer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
