# Generated by Django 4.2.16 on 2024-12-06 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_dancerprofile_danceruser"),
    ]

    operations = [
        migrations.AddField(
            model_name="dancepost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
