# Generated by Django 4.2.16 on 2024-12-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_dancepost_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="dancerprofile",
            name="profile_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="profile_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
