# Generated by Django 4.2.16 on 2024-12-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_dancerprofile_profile_image_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dancerprofile", old_name="profile_image_url", new_name="image",
        ),
        migrations.RenameField(
            model_name="recruiterprofile",
            old_name="profile_image_url",
            new_name="image",
        ),
    ]
